# Desativa os Dev Services automáticos que tentam usar o Docker local
quarkus.datasource.devservices.enabled=false

# Desativa a validação ativa do Hibernate ORM enquanto não temos entidades @Entity
quarkus.hibernate-orm.active=false