# =============================================================================
# CONFIGURAÇÕES DA FONTE DE DADOS (DATABASE)
# =============================================================================
# Ativa o driver do PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=nextgen_admin
quarkus.datasource.password=checkout_secure_pass

# URL de Conexão apontando para a porta que você configurou no Docker (5435)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5435/nextgen_checkout

# Desativa o Dev Services automático já que gerenciamos o banco via Docker Compose
quarkus.datasource.devservices.enabled=false

# =============================================================================
# CONFIGURAÇÕES DO HIBERNATE ORM (JPA)
# =============================================================================
# Reativa o Hibernate (havíamos desligado temporariamente)
quarkus.hibernate-orm.active=true

# Estratégia de criação de tabelas: 'update' ajusta o banco automaticamente quando criamos entidades Java
quarkus.hibernate-orm.database.generation=update

# Ativa o log das queries SQL no terminal para podermos debugar o que o Panache está executando
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Altera a porta HTTP padrão de 8080 para 8081
quarkus.http.port=8087

# -----------------------------------------------------------------------------
# CONFIGURAÇÕES DE CORS (Permite conexões do Angular)
# -----------------------------------------------------------------------------
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS